#pragma once

// Generated by ml/rhythm/run_training.py from subject-independent,
// ECG-referenced MIMIC PERform AF data. Do not edit by hand.
namespace RhythmModel {
constexpr unsigned int MODEL_VERSION = 1;
constexpr unsigned int FEATURE_COUNT = 6;
// Input order: IBI CV, RMSSD/mean IBI, pNN50, max IBI jump/mean,
// signal quality (gate only, zero weight), heart-rate out-of-range score.
constexpr signed char WEIGHTS[FEATURE_COUNT] = {72, 60, 124, 40, 0, -6};
constexpr int BIAS = -17264;
constexpr float SCORE_SCALE = 8017.0f;
constexpr float AF_THRESHOLD = 0.850000f;
constexpr unsigned int MODEL_BYTES = sizeof(WEIGHTS) + sizeof(BIAS) +
                                     sizeof(SCORE_SCALE) + sizeof(AF_THRESHOLD);
}  // namespace RhythmModel
